# Generated by Django 3.2.9 on 2021-12-11 21:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookinginfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bookingkey', models.CharField(max_length=255, null=True)),
                ('No_of_People', models.PositiveIntegerField(default=0)),
                ('State', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('Service', models.CharField(max_length=255, null=True)),
                ('Start_Date', models.DateField(default=datetime.date.today)),
                ('End_Date', models.DateField(default=datetime.date.today)),
                ('Total_Cost', models.PositiveIntegerField(null=True)),
                ('Amount_Paid', models.PositiveIntegerField(null=True)),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Mode_of_payment', models.CharField(max_length=255, null=True)),
                ('Additional_info', models.CharField(max_length=255, null=True)),
                ('Created_by', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('PhoneNo', models.CharField(max_length=255)),
                ('Age', models.PositiveIntegerField(null=True)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Aadhar_Card_No', models.CharField(max_length=12, null=True)),
                ('DOB', models.DateField(default=datetime.date.today, null=True)),
                ('Address', models.CharField(max_length=255, null=True)),
                ('City', models.CharField(max_length=255, null=True)),
                ('State', models.CharField(max_length=255, null=True)),
                ('Occupation', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='entryform',
            name='Image_1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='entryform',
            name='Image_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='entryform',
            name='State_Name',
            field=models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CT', 'Chhattisgarh'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JK', 'Jammu and Kashmir'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('MP', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OR', 'Odisha'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TG', 'Telangana'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('UT', 'Uttarakhand'), ('WB', 'West Bengal'), ('AN', 'Andaman and Nicobar Islands'), ('CH', 'Chandigarh'), ('DN', 'Dadra and Nagar Haveli'), ('DD', 'Daman and Diu'), ('LD', 'Lakshadweep'), ('DL', 'Delhi'), ('PY', 'Puducherry')], max_length=255),
        ),
        migrations.CreateModel(
            name='Hotelinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('State', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('Checkin_Date', models.DateField(default=datetime.date.today)),
                ('Checktout_Date', models.DateField(default=datetime.date.today)),
                ('No_of_rooms', models.PositiveIntegerField()),
                ('Room_Type', models.CharField(max_length=255)),
                ('Meal_Plan', models.CharField(max_length=255)),
                ('Room_Sharing_Option', models.CharField(max_length=255)),
                ('Hotel_Contact_Name', models.CharField(max_length=255)),
                ('Hotel_Contact_No', models.CharField(max_length=255)),
                ('Total_Cost', models.PositiveIntegerField()),
                ('Amount_Paid', models.PositiveIntegerField(null=True)),
                ('Bookingkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.bookinginfo')),
            ],
        ),
        migrations.AddField(
            model_name='bookinginfo',
            name='personal_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.personalinfo'),
        ),
    ]
