# Generated by Django 3.2.9 on 2021-12-11 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20211212_0237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinginfo',
            old_name='Date',
            new_name='Due_Date',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='Age',
        ),
        migrations.AddField(
            model_name='bookinginfo',
            name='PaymentDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='bookinginfo',
            name='Service_Status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
