# Generated by Django 3.2.9 on 2021-12-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20211212_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginfo',
            name='Trip_Name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
