# Generated by Django 3.2.9 on 2021-12-12 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_bookinginfo_trip_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinginfo',
            old_name='PaymentDate',
            new_name='BookingDate',
        ),
    ]
