# Generated by Django 3.2.9 on 2021-12-13 16:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_rename_paymentdate_bookinginfo_bookingdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_Name', models.CharField(max_length=255)),
                ('Driver_Name', models.CharField(max_length=255)),
                ('Driver_Phone_No', models.CharField(max_length=255)),
                ('Start_Date', models.DateField(default=datetime.date.today)),
                ('End_date', models.DateField(default=datetime.date.today)),
                ('Start_Location', models.CharField(max_length=255)),
                ('End_Location', models.CharField(max_length=255)),
                ('Total_Cost', models.PositiveIntegerField()),
                ('Additional_info', models.CharField(max_length=255)),
                ('Bookingkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.bookinginfo')),
            ],
        ),
        migrations.CreateModel(
            name='Ticketinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_of_ticket', models.CharField(max_length=255)),
                ('No_of_tickets', models.PositiveIntegerField()),
                ('Departure_Date', models.DateField(default=datetime.date.today)),
                ('Arrival_Date', models.DateField(default=datetime.date.today)),
                ('Departure_city', models.CharField(max_length=255)),
                ('Arrival_city', models.CharField(max_length=255)),
                ('Total_Cost', models.PositiveIntegerField()),
                ('Amount_Paid', models.PositiveIntegerField(null=True)),
                ('Additional_info', models.CharField(max_length=255)),
                ('Bookingkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.bookinginfo')),
            ],
        ),
        migrations.CreateModel(
            name='Paymentinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_Type', models.CharField(max_length=255)),
                ('Amount', models.PositiveBigIntegerField()),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Mode_of_payment', models.CharField(max_length=255)),
                ('Additional_info', models.CharField(max_length=255)),
                ('Verify', models.CharField(max_length=255)),
                ('Bookingkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.bookinginfo')),
            ],
        ),
        migrations.CreateModel(
            name='Activitiesinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_activity', models.CharField(max_length=255)),
                ('State', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('No_of_People', models.PositiveIntegerField()),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Vendor_Name', models.CharField(max_length=255)),
                ('Vendor_Contact_No', models.CharField(max_length=255)),
                ('Total_Cost', models.PositiveIntegerField()),
                ('Bookingkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.bookinginfo')),
            ],
        ),
    ]
