# Generated by Django 3.2.9 on 2021-12-14 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_activitiesinfo_paymentinfo_ticketinfo_transportinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='Bookingkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.personalinfo'),
        ),
    ]
