# Generated by Django 3.2.9 on 2021-12-15 12:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_alter_paymentinfo_bookingkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guestinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('PhoneNo', models.CharField(max_length=255)),
                ('DOB', models.DateField(default=datetime.date.today, null=True)),
                ('Gender', models.CharField(max_length=255, null=True)),
                ('Occupation', models.CharField(max_length=255, null=True)),
                ('Address', models.CharField(max_length=255, null=True)),
                ('City', models.CharField(max_length=255, null=True)),
                ('State', models.CharField(max_length=255, null=True)),
                ('Aadhar_Card_No', models.CharField(max_length=12, null=True)),
                ('Bookingkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.bookinginfo')),
            ],
        ),
    ]
