# Generated by Django 3.2.9 on 2021-12-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_guestinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestinfo',
            name='Membertype',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
