# Generated by Django 3.2.9 on 2021-12-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0010_guestinfo_membertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelinfo',
            old_name='City',
            new_name='Hcity',
        ),
        migrations.RenameField(
            model_name='hotelinfo',
            old_name='Name',
            new_name='Hname',
        ),
        migrations.RenameField(
            model_name='hotelinfo',
            old_name='State',
            new_name='Hstate',
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='Cemail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='Cname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='Cnumber',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
