# Generated by Django 3.2.9 on 2021-12-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0011_auto_20211217_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestinfo',
            name='Membertype',
        ),
        migrations.AddField(
            model_name='guestinfo',
            name='IsPrime',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
