# Generated by Django 3.2.9 on 2021-12-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0012_auto_20211217_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitiesinfo',
            name='Additional_info',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
