# Generated by Django 3.2.9 on 2021-12-18 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0013_activitiesinfo_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelinfo',
            name='Checkin_Date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='hotelinfo',
            name='Checktout_Date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='hotelinfo',
            name='Hcity',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotelinfo',
            name='Hotel_Contact_Name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotelinfo',
            name='Hotel_Contact_No',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotelinfo',
            name='Hstate',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotelinfo',
            name='Meal_Plan',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotelinfo',
            name='No_of_rooms',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hotelinfo',
            name='Room_Sharing_Option',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotelinfo',
            name='Room_Type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotelinfo',
            name='Total_Cost',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
