# Generated by Django 3.2.9 on 2021-12-19 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0014_auto_20211218_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Membertype', models.CharField(max_length=255)),
                ('Bookingkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.bookinginfo')),
                ('Personalkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.personalinfo')),
            ],
        ),
        migrations.DeleteModel(
            name='Guestinfo',
        ),
    ]
