# Generated by Django 3.2.9 on 2021-12-19 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0015_auto_20211220_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connections',
            name='Personalkey',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='form.personalinfo'),
        ),
    ]
