# Generated by Django 3.2.9 on 2021-12-19 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0016_alter_connections_personalkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelinfo',
            name='Cname',
        ),
        migrations.RemoveField(
            model_name='hotelinfo',
            name='Cnumber',
        ),
    ]
