# Generated by Django 3.2.9 on 2021-12-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0017_auto_20211220_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginfo',
            name='Due_amount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
