# Generated by Django 3.2.9 on 2021-12-21 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0018_bookinginfo_due_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelinfo',
            old_name='Cemail',
            new_name='Hemail',
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='Additional_info',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookinginfo',
            name='personal_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bdetails', to='form.personalinfo'),
        ),
    ]
