# Generated by Django 3.2.9 on 2021-12-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0019_auto_20211221_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelinfo',
            name='Due_Amount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
