# Generated by Django 3.2.9 on 2021-12-23 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0020_hotelinfo_due_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginfo',
            name='personal_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.personalinfo'),
        ),
    ]
