# Generated by Django 3.2.9 on 2021-12-23 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0022_paymentinfo_hpaymentskey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinfo',
            name='Hpaymentskey',
        ),
    ]
