# Generated by Django 3.2.9 on 2021-12-23 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0025_remove_paymentinfo_hpaymentskey'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelinfo',
            name='Payments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='form.paymentinfo'),
        ),
    ]
