# Generated by Django 3.2.10 on 2021-12-23 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0027_auto_20211223_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='Hpaymentskey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hp', to='form.hotelinfo'),
        ),
    ]
