# Generated by Django 3.2.9 on 2021-12-25 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0028_alter_paymentinfo_hpaymentskey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginfo',
            name='Amount_Paid',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookinginfo',
            name='personal_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bdetails', to='form.personalinfo'),
        ),
    ]
