# Generated by Django 3.2.9 on 2021-12-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0029_auto_20211225_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginfo',
            name='Amount_Paid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookinginfo',
            name='Due_amount',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
