# Generated by Django 3.2.9 on 2021-12-25 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0030_auto_20211225_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='Apaymentskey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ap', to='form.activitiesinfo'),
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='Tpaymentskey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tp', to='form.transportinfo'),
        ),
    ]
