# Generated by Django 3.2.9 on 2021-12-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0031_auto_20211226_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitiesinfo',
            name='Amount_Paid',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='activitiesinfo',
            name='Due_Amount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transportinfo',
            name='Amount_Paid',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transportinfo',
            name='Due_Amount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
