# Generated by Django 3.2.9 on 2021-12-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0032_auto_20211226_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelinfo',
            name='Due_Amount',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
