# Generated by Django 3.2.9 on 2021-12-26 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0034_alter_hotelinfo_due_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelinfo',
            old_name='Due_Amount',
            new_name='due_amount',
        ),
    ]
