# Generated by Django 3.2.9 on 2021-12-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0035_rename_due_amount_hotelinfo_due_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelinfo',
            name='due_amount',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
