# Generated by Django 3.2.9 on 2021-12-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0036_alter_hotelinfo_due_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitiesinfo',
            name='Due_Amount',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
