# Generated by Django 3.2.9 on 2021-12-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0037_alter_activitiesinfo_due_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginfo',
            name='Amount_Paid',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bookinginfo',
            name='Due_amount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
