# Generated by Django 3.2.9 on 2021-12-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0038_auto_20211227_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitiesinfo',
            name='Service_Status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotelinfo',
            name='Service_Status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transportinfo',
            name='Service_Status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activitiesinfo',
            name='No_of_People',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookinginfo',
            name='No_of_People',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
