# Generated by Django 3.2.9 on 2021-12-30 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0039_auto_20211229_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='Tipaymentskey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tip', to='form.ticketinfo'),
        ),
        migrations.AddField(
            model_name='ticketinfo',
            name='Due_Amount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ticketinfo',
            name='Service_Status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
