# Generated by Django 3.2.9 on 2022-01-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0041_venderinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginfo',
            name='Trello_link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
