# Generated by Django 3.2.9 on 2022-01-06 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0042_bookinginfo_trello_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginfo',
            name='Due_Date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
