# Generated by Django 3.2.9 on 2022-01-12 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0045_alter_bookinginfo_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginfo',
            name='Due_Date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
