# Generated by Django 3.2.9 on 2022-01-12 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0046_alter_bookinginfo_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.TextField()),
                ('User', models.CharField(max_length=255)),
                ('Bookingkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.bookinginfo')),
            ],
        ),
    ]
