# Generated by Django 3.2.9 on 2022-01-12 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0048_comment_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
