# Generated by Django 3.2.9 on 2022-01-14 15:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0050_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Bookingkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp', to='form.bookinginfo'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
