# Generated by Django 3.2.9 on 2022-01-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0050_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
