# Generated by Django 3.2.9 on 2022-01-13 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0051_alter_comment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Bookingkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp', to='form.bookinginfo'),
        ),
    ]
