# Generated by Django 3.2.9 on 2022-01-14 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0051_auto_20220114_2046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
